server:
  port: 8080
spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_qycexam
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  config-location: classpath:static/mybatis/mybatis.xml
  mapper-locations: classpath:static/mybatis/mapper/*.xml
